# Generated by Django 2.2.7 on 2019-12-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Bio', models.TextField()),
                ('Registration_date', models.DateTimeField(auto_now_add=True)),
                ('Facebook_link', models.CharField(max_length=100)),
                ('Instagram_link', models.CharField(max_length=100)),
                ('Twitter_link', models.CharField(max_length=100)),
                ('Profile_image', models.ImageField(blank=True, max_length=255, upload_to='pictures/%Y/%m/%d/')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=50)),
                ('entry_text', models.TextField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Category')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
